//
//  DiopsPacketCommand.swift
//  SwiftCmdTest
//
//  Created by 윤성빈 on 2020/08/14.
//  Copyright © 2020 윤성빈. All rights reserved.
//

import Foundation

enum OPINSResult : UInt32
{
    case USERLOGINOK = 0,
    USERLOGINDOESNOTEXISTUSERINFO = 1,
    USERLOGINNOLICENSE = 2,
    USERLOGINALREADYCONNECTED = 3,
    USERLOGINNOCONNECT = 4,
    USERLOGINNOTCONFIGMANAGER = 5,
    USERLOGINPASSWORDMISSMATCH = 6,
    //라이센스
    LICENSEREGISTEROK = 100,
    LICENSEDATAINFOOK = 102,
    LICENSEDATAINFOFAIL = 103,
    LICENSEINFOCHANGEOK = 104,
    LICENSEINFOCHANGEFAIL = 105,
    LICENSESYSTEMKEYOK = 106,
    LICENSESYSTEMKEYFAIL = 107,
    LICENSEEXPIRATION = 108,
    LICENSEINSUFFICIENT = 109,
    LICENSEOK = 110,
    //데이터 관련
    DATACHANGEOK = 200,
    DATACHANGEFAIL = 201,
    DATAINFOOK = 202,
    DATAINFOFAIL = 203,
    //저장 정보
    RECDATEINFOOK = 204,
    RECDATEINFOFAIL = 205,
    RECMININFOOK = 206,
    RECMININFOFAIL = 207,
    //StreamFile 전송 정보
    SENDSTREAMSUCCESS = 208,
    SENDSTREAMFAIL = 209
}


enum OPINSPTZCommand : Int32
{
    case OPINS_PTZ_UNKNOWNCOMMAND = -1,
         OPINS_PTZ_LEFT_UP,
         OPINS_PTZ_UP,
         OPINS_PTZ_RIGHT_UP,
         
         OPINS_PTZ_LEFT,
         OPINS_PTZ_CENTER,
         OPINS_PTZ_RIGHT,
         
         OPINS_PTZ_LEFT_DOWN,
         OPINS_PTZ_DOWN,
         OPINS_PTZ_RIGHT_DOWN,
         
         OPINS_PTZ_FOCUS_IN,
         OPINS_PTZ_FOCUS_OUT,
         
         OPINS_PTZ_ZOOM_IN,
         OPINS_PTZ_ZOOM_OUT,
         
         OPINS_PTZ_AUTOPAN_ON,
         OPINS_PTZ_AUTOPAN_OFF,
         
         OPINS_PTZ_TOURING_START,
         OPINS_PTZ_TOURING_STOP,
         
         OPINS_PTZ_POWER_ON,
         OPINS_PTZ_POWER_OFF,
         
         OPINS_PTZ_WIPER_ON,
         OPINS_PTZ_WIPER_OFF,
         
         OPINS_PTZ_LAMP_ON,
         OPINS_PTZ_LAMP_OFF,
         
         OPINS_PTZ_AUX_ON,
         OPINS_PTZ_AUX_OFF,
         
         OPINS_PTZ_CONTROL_LOCK,
         OPINS_PTZ_CONTROL_STOP,
         OPINS_PTZ_CONTROL_UNLOCK,
         
         OPINS_PTZ_PRESET_MOVE,
         OPINS_PTZ_PRESET_ADD,
         OPINS_PTZ_PRESET_MOD,
         OPINS_PTZ_PRESET_DEL,
         
         OPINS_PTZ_SPEED_CHANGE,
         OPINS_PTZ_OSD_MENU_ON,
         OPINS_PTZ_OSD_MENU_ENTER,
         OPINS_PTZ_OSD_MENU_ESC,
         
         OPINS_PTZ_PRESET_HOME,
         
         OPINS_PTZ_GET_POSITION,
         OPINS_PTZ_SET_POSITION,
         
         OPINS_PTZ_RECTANGLE_PTZ_IN,
         OPINS_PTZ_RECTANGLE_PTZ_OUT,
         
         OPINS_PTZ_RELATIVE_MOVE,
         OPINS_PTZ_SPEED_DEFAULT,
         
         OPINS_PTZ_MAX_CONTROLS
}

enum OPINSProtocolCommand : Int64
{
    case OPINS_CMD_UNKNOWN                                         = -1,
    OPINS_CMD_REQ_LOGIN                                            = 0x00,
    OPINS_CMD_RES_LOGIN                                            = 0x01,
    OPINS_CMD_REQ_DEVICEINFO                                       = 0x02,
    OPINS_CMD_RES_DEVICEINFO                                       = 0x03,
    OPINS_CMD_REQ_DEVICESTAT                                       = 0x04,
    OPINS_CMD_RES_DEVICESTAT                                       = 0x05,
    OPINS_CMD_REQ_DEVICEADD                                        = 0x06,
    OPINS_CMD_RES_DEVICEADD                                        = 0x07,
    OPINS_CMD_REQ_DEVICEMOD                                        = 0x08,
    OPINS_CMD_RES_DEVICEMOD                                        = 0x09,
    OPINS_CMD_REQ_DEVICEDEL                                        = 0x0A,
    OPINS_CMD_RES_DEVICEDEL                                        = 0x0B,
    OPINS_CMD_REQ_CAMERAINFO                                       = 0x0C,
    OPINS_CMD_RES_CAMERAINFO                                       = 0x0D,
    OPINS_CMD_REQ_AUDIOINFO                                        = 0x0E,
    OPINS_CMD_RES_AUDIOINFO                                        = 0x0F,
    OPINS_CMD_REQ_SENSORINFO                                       = 0x10,
    OPINS_CMD_RES_SENSORINFO                                       = 0x11,
    OPINS_CMD_REQ_RELAYINFO                                        = 0x12,
    OPINS_CMD_RES_RELAYINFO                                        = 0x13,
    OPINS_CMD_REQ_USERINFO                                         = 0x14,
    OPINS_CMD_RES_USERINFO                                         = 0x15,
    OPINS_CMD_REQ_USERADD                                          = 0x16,
    OPINS_CMD_RES_USERADD                                          = 0x17,
    OPINS_CMD_REQ_USERMOD                                          = 0x18,
    OPINS_CMD_RES_USERMOD                                          = 0x19,
    OPINS_CMD_REQ_USERDEL                                          = 0x1A,
    OPINS_CMD_RES_USERDEL                                          = 0x1B,
    OPINS_CMD_REQ_SERVERINFO                                       = 0x1C,
    OPINS_CMD_RES_SERVERINFO                                       = 0x1D,
    OPINS_CMD_REQ_SERVERADD                                        = 0x1E,
    OPINS_CMD_RES_SERVERADD                                        = 0x1F,
    OPINS_CMD_REQ_SERVERMOD                                        = 0x20,
    OPINS_CMD_RES_SERVERMOD                                        = 0x21,
    OPINS_CMD_REQ_SERVERDEL                                        = 0x22,
    OPINS_CMD_RES_SERVERDEL                                        = 0x23,
    OPINS_CMD_REQ_CAMERAADD                                        = 0x24,
    OPINS_CMD_RES_CAMERAADD                                        = 0x25,
    OPINS_CMD_REQ_CAMERAMOD                                        = 0x26,
    OPINS_CMD_RES_CAMERAMOD                                        = 0x27,
    OPINS_CMD_REQ_CAMERADEL                                        = 0x28,
    OPINS_CMD_RES_CAMERADEL                                        = 0x29,
    OPINS_CMD_REQ_AUDIOADD                                         = 0x2A,
    OPINS_CMD_RES_AUDIOADD                                         = 0x2B,
    OPINS_CMD_REQ_AUDIOMOD                                         = 0x2C,
    OPINS_CMD_RES_AUDIOMOD                                         = 0x2D,
    OPINS_CMD_REQ_AUDIODEL                                         = 0x2E,
    OPINS_CMD_RES_AUDIODEL                                         = 0x2F,
    OPINS_CMD_REQ_SENSORADD                                        = 0x30,
    OPINS_CMD_RES_SENSORADD                                        = 0x31,
    OPINS_CMD_REQ_SENSORMOD                                        = 0x32,
    OPINS_CMD_RES_SENSORMOD                                        = 0x33,
    OPINS_CMD_REQ_SENSORDEL                                        = 0x34,
    OPINS_CMD_RES_SENSORDEL                                        = 0x35,
    OPINS_CMD_REQ_RELAYADD                                         = 0x36,
    OPINS_CMD_RES_RELAYADD                                         = 0x37,
    OPINS_CMD_REQ_RELAYMOD                                         = 0x38,
    OPINS_CMD_RES_RELAYMOD                                         = 0x39,
    OPINS_CMD_REQ_RELAYDEL                                         = 0x3A,
    OPINS_CMD_RES_RELAYDEL                                         = 0x3B,
    OPINS_CMD_REQ_DEVICEMODELINFO                                  = 0x3C,
    OPINS_CMD_RES_DEVICEMODELINFO                                  = 0x3D,
    OPINS_CMD_REQ_DEVICEMANUFACTURERINFO                           = 0x3E,
    OPINS_CMD_RES_DEVICEMANUFACTURERINFO                           = 0x3F,
    OPINS_CMD_REQ_SERVERSETTINGINFO                                = 0x40,
    OPINS_CMD_RES_SERVERSETTINGINFO                                = 0x41,
    OPINS_CMD_REQ_SYSTEMSETTINGINFO                                = 0x42,
    OPINS_CMD_RES_SYSTEMSETTINGINFO                                = 0x43,
    OPINS_CMD_REQ_SERVERSETTINGADD                                 = 0x44,
    OPINS_CMD_RES_SERVERSETTINGADD                                 = 0x45,
    OPINS_CMD_REQ_SERVERSETTINGMOD                                 = 0x46,
    OPINS_CMD_RES_SERVERSETTINGMOD                                 = 0x47,
    OPINS_CMD_REQ_SERVERSETTINGDEL                                 = 0x48,
    OPINS_CMD_RES_SERVERSETTINGDEL                                 = 0x49,
    OPINS_CMD_REQ_SYSTEMSETTINGADD                                 = 0x4A,
    OPINS_CMD_RES_SYSTEMSETTINGADD                                 = 0x4B,
    OPINS_CMD_REQ_SYSTEMSETTINGMOD                                 = 0x4C,
    OPINS_CMD_RES_SYSTEMSETTINGMOD                                 = 0x4D,
    OPINS_CMD_REQ_SYSTEMSETTINGDEL                                 = 0x4E,
    OPINS_CMD_RES_SYSTEMSETTINGDEL                                 = 0x4F,
    OPINS_CMD_REQ_OPINSINFOALLDATA                                 = 0x50,
    OPINS_CMD_RES_OPINSINFOALLDATA                                 = 0x51,
    OPINS_CMD_REQ_DEVICEMODELADD                                   = 0x52,
    OPINS_CMD_RES_DEVICEMODELADD                                   = 0x53,
    OPINS_CMD_REQ_DEVICEMODELMOD                                   = 0x54,
    OPINS_CMD_RES_DEVICEMODELMOD                                   = 0x55,
    OPINS_CMD_REQ_DEVICEMODELDEL                                   = 0x56,
    OPINS_CMD_RES_DEVICEMODELDEL                                   = 0x57,
    OPINS_CMD_REQ_DEVICEMANUFACTURERADD                            = 0x58,
    OPINS_CMD_RES_DEVICEMANUFACTURERADD                            = 0x59,
    OPINS_CMD_REQ_DEVICEMANUFACTURERMOD                            = 0x5A,
    OPINS_CMD_RES_DEVICEMANUFACTURERMOD                            = 0x5B,
    OPINS_CMD_REQ_DEVICEMANUFACTURERDEL                            = 0x5C,
    OPINS_CMD_RES_DEVICEMANUFACTURERDEL                            = 0x5D,
    OPINS_CMD_REQ_USERGROUPINFO                                    = 0x5E,
    OPINS_CMD_RES_USERGROUPINFO                                    = 0x5F,
    OPINS_CMD_REQ_USERGROUPADD                                        = 0x60,
    OPINS_CMD_RES_USERGROUPADD                                        = 0x61,
    OPINS_CMD_REQ_USERGROUPMOD                                        = 0x62,
    OPINS_CMD_RES_USERGROUPMOD                                        = 0x63,
    OPINS_CMD_REQ_USERGROUPDEL                                        = 0x64,
    OPINS_CMD_RES_USERGROUPDEL                                        = 0x65,
    OPINS_CMD_REQ_FOLDERINFO                                        = 0x66,
    OPINS_CMD_RES_FOLDERINFO                                        = 0x67,
    OPINS_CMD_REQ_FOLDERADD                                        = 0x68,
    OPINS_CMD_RES_FOLDERADD                                        = 0x69,
    OPINS_CMD_REQ_FOLDERMOD                                        = 0x6A,
    OPINS_CMD_RES_FOLDERMOD                                        = 0x6B,
    OPINS_CMD_REQ_FOLDERDEL                                        = 0x6C,
    OPINS_CMD_RES_FOLDERDEL                                        = 0x6D,
    OPINS_CMD_REQ_DEVICEPERMISSIONINFO                                = 0x6E,
    OPINS_CMD_RES_DEVICEPERMISSIONINFO                                = 0x6F,
    OPINS_CMD_REQ_DEVICEPERMISSIONADD                                = 0x70,
    OPINS_CMD_RES_DEVICEPERMISSIONADD                                = 0x71,
    OPINS_CMD_REQ_DEVICEPERMISSIONMOD                                = 0x72,
    OPINS_CMD_RES_DEVICEPERMISSIONMOD                                = 0x73,
    OPINS_CMD_REQ_DEVICEPERMISSIONDEL                                = 0x74,
    OPINS_CMD_RES_DEVICEPERMISSIONDEL                                = 0x75,
    OPINS_CMD_REQ_LICENSEINFO                                        = 0x76,
    OPINS_CMD_RES_LICENSEINFO                                        = 0x77,
    OPINS_CMD_REQ_LICENSEADD                                        = 0x78,
    OPINS_CMD_RES_LICENSEADD                                        = 0x79,
    OPINS_CMD_REQ_LICENSEMOD                                        = 0x7A,
    OPINS_CMD_RES_LICENSEMOD                                        = 0x7B,
    OPINS_CMD_REQ_LICENSEDEL                                        = 0x7C,
    OPINS_CMD_RES_LICENSEDEL                                        = 0x7D,
    OPINS_CMD_REQ_USERREGISTERDEVICEINFO                            = 0x7E,
    OPINS_CMD_RES_USERREGISTERDEVICEINFO                            = 0x7F,
    OPINS_CMD_REQ_USERREGISTERDEVICEADD                            = 0x80,
    OPINS_CMD_RES_USERREGISTERDEVICEADD                            = 0x81,
    OPINS_CMD_REQ_USERREGISTERDEVICEMOD                            = 0x82,
    OPINS_CMD_RES_USERREGISTERDEVICEMOD                            = 0x83,
    OPINS_CMD_REQ_USERREGISTERDEVICEDEL                            = 0x84,
    OPINS_CMD_RES_USERREGISTERDEVICEDEL                            = 0x85,
    OPINS_CMD_REQ_USERREGISTERDEVICEGROUPINFO                      = 0x86,
    OPINS_CMD_RES_USERREGISTERDEVICEGROUPINFO                      = 0x87,
    OPINS_CMD_REQ_USERREGISTERDEVICEGROUPADD                        = 0x88,
    OPINS_CMD_RES_USERREGISTERDEVICEGROUPADD                        = 0x89,
    OPINS_CMD_REQ_USERREGISTERDEVICEGROUPMOD                        = 0x8A,
    OPINS_CMD_RES_USERREGISTERDEVICEGROUPMOD                        = 0x8B,
    OPINS_CMD_REQ_USERREGISTERDEVICEGROUPDEL                        = 0x8C,
    OPINS_CMD_RES_USERREGISTERDEVICEGROUPDEL                        = 0x8D,
    OPINS_CMD_REQ_USERPERMISSIONINFO                               = 0x8E,
    OPINS_CMD_RES_USERPERMISSIONINFO                               = 0x8F,
    OPINS_CMD_REQ_USERPERMISSIONADD                                = 0x90,
    OPINS_CMD_RES_USERPERMISSIONADD                                = 0x91,
    OPINS_CMD_REQ_USERPERMISSIONMOD                                = 0x92,
    OPINS_CMD_RES_USERPERMISSIONMOD                                = 0x93,
    OPINS_CMD_REQ_USERPERMISSIONDEL                                = 0x94,
    OPINS_CMD_RES_USERPERMISSIONDEL                                = 0x95,
    OPINS_CMD_REQ_LICENSEDATAINFO                                  = 0x96,
    OPINS_CMD_RES_LICENSEDATAINFO                                  = 0x97,
    OPINS_CMD_REQ_SYSTEMKEY                                        = 0x98,
    OPINS_CMD_RES_SYSTEMKEY                                        = 0x99,
    OPINS_CMD_REQ_EVENT                                            = 0x9A,
    OPINS_CMD_RES_EVENT                                            = 0x9B,
    OPINS_CMD_REQ_EVENTCODEINFO                                    = 0x9C,
    OPINS_CMD_RES_EVENTCODEINFO                                    = 0x9D,
    OPINS_CMD_REQ_EVENTCODEADD                                        = 0x9E,
    OPINS_CMD_RES_EVENTCODEADD                                        = 0x9F,
    OPINS_CMD_REQ_EVENTCODEMOD                                        = 0xA0,
    OPINS_CMD_RES_EVENTCODEMOD                                        = 0xA1,
    OPINS_CMD_REQ_EVENTCODEDEL                                        = 0xA2,
    OPINS_CMD_RES_EVENTCODEDEL                                        = 0xA3,
    OPINS_CMD_REQ_SYSTEMLOGCODEINFO                                = 0xA4,
    OPINS_CMD_RES_SYSTEMLOGCODEINFO                                = 0xA5,
    OPINS_CMD_REQ_SYSTEMLOGCODEADD                                    = 0xA6,
    OPINS_CMD_RES_SYSTEMLOGCODEADD                                    = 0xA7,
    OPINS_CMD_REQ_SYSTEMLOGCODEMOD                                    = 0xA8,
    OPINS_CMD_RES_SYSTEMLOGCODEMOD                                    = 0xA9,
    OPINS_CMD_REQ_SYSTEMLOGCODEDEL                                    = 0xAA,
    OPINS_CMD_RES_SYSTEMLOGCODEDEL                                    = 0xAB,
    OPINS_CMD_REQ_SCHEDULEINFO                                        = 0xAC,
    OPINS_CMD_RES_SCHEDULEINFO                                        = 0xAD,
    OPINS_CMD_REQ_SCHEDULEADD                                        = 0xAE,
    OPINS_CMD_RES_SCHEDULEADD                                        = 0xAF,
    OPINS_CMD_REQ_SCHEDULEMOD                                        = 0xB0,
    OPINS_CMD_RES_SCHEDULEMOD                                        = 0xB1,
    OPINS_CMD_REQ_SCHEDULEDEL                                        = 0xB2,
    OPINS_CMD_RES_SCHEDULEDEL                                        = 0xB3,
    OPINS_CMD_REQ_RECORDINGRULEINFO                                = 0xB4,
    OPINS_CMD_RES_RECORDINGRULEINFO                                = 0xB5,
    OPINS_CMD_REQ_RECORDINGRULEADD                                    = 0xB6,
    OPINS_CMD_RES_RECORDINGRULEADD                                    = 0xB7,
    OPINS_CMD_REQ_RECORDINGRULEMOD                                    = 0xB8,
    OPINS_CMD_RES_RECORDINGRULEMOD                                    = 0xB9,
    OPINS_CMD_REQ_RECORDINGRULEDEL                                    = 0xBA,
    OPINS_CMD_RES_RECORDINGRULEDEL                                    = 0xBB,
    OPINS_CMD_REQ_EVENTRULEINFO                                    = 0xBC,
    OPINS_CMD_RES_EVENTRULEINFO                                    = 0xBD,
    OPINS_CMD_REQ_EVENTRULEADD                                        = 0xBE,
    OPINS_CMD_RES_EVENTRULEADD                                        = 0xBF,
    OPINS_CMD_REQ_EVENTRULEMOD                                        = 0xC0,
    OPINS_CMD_RES_EVENTRULEMOD                                        = 0xC1,
    OPINS_CMD_REQ_EVENTRULEDEL                                        = 0xC2,
    OPINS_CMD_RES_EVENTRULEDEL                                        = 0xC3,
    OPINS_CMD_REQ_EVENTSTORAGEINFO                                    = 0xC4,
    OPINS_CMD_RES_EVENTSTORAGEINFO                                    = 0xC5,
    OPINS_CMD_REQ_EVENTSTORAGEADD                                    = 0xC6,
    OPINS_CMD_RES_EVENTSTORAGEADD                                    = 0xC7,
    OPINS_CMD_REQ_EVENTSTORAGEMOD                                    = 0xC8,
    OPINS_CMD_RES_EVENTSTORAGEMOD                                    = 0xC9,
    OPINS_CMD_REQ_EVENTSTORAGEDEL                                    = 0xCA,
    OPINS_CMD_RES_EVENTSTORAGEDEL                                    = 0xCB,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGEINFO                                = 0xCC,
    OPINS_CMD_RES_SYSTEMLOGSTORAGEINFO                                = 0xCD,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGEADD                                = 0xCE,
    OPINS_CMD_RES_SYSTEMLOGSTORAGEADD                                = 0xCF,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGEMOD                                = 0xD0,
    OPINS_CMD_RES_SYSTEMLOGSTORAGEMOD                                = 0xD1,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGEDEL                                = 0xD2,
    OPINS_CMD_RES_SYSTEMLOGSTORAGEDEL                                = 0xD3,
    OPINS_CMD_REQ_EVENTSTORAGE_DISTINCTEVENTCODE                   = 0xD4,
    OPINS_CMD_RES_EVENTSTORAGE_DISTINCTEVENTCODE                   = 0xD5,
    OPINS_CMD_REQ_EVENTSTORAGE_DISTINCTDEVICE                      = 0xD6,
    OPINS_CMD_RES_EVENTSTORAGE_DISTINCTDEVICE                      = 0xD7,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGE_DISTINCTSYSTEMLOGCODE           = 0xD8,
    OPINS_CMD_RES_SYSTEMLOGSTORAGE_DISTINCTSYSTEMLOGCODE           = 0xD9,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGE_DISTINCTTARGETTYPE              = 0xDA,
    OPINS_CMD_RES_SYSTEMLOGSTORAGE_DISTINCTTARGETTYPE              = 0xDB,
    OPINS_CMD_REQ_SYSTEMLOGSTORAGE_DISTINCTTARGET                  = 0xDC,
    OPINS_CMD_RES_SYSTEMLOGSTORAGE_DISTINCTTARGET                  = 0xDD,
    OPINS_CMD_REQ_SERVERSTAT                                        = 0xDE,
    OPINS_CMD_RES_SERVERSTAT                                        = 0xDF,
    OPINS_CMD_REQ_OPINSINFODATACHANGE                              = 0x108,
    OPINS_CMD_RES_OPINSINFODATACHANGE                              = 0x109,
    OPINS_CMD_REQ_STREAM                       = 0x1000,
    OPINS_CMD_RES_STREAM                        = 0x1002,
    OPINS_CMD_REQ_PTZCONTROL                    = 0x1003,
    OPINS_CMD_RES_PTZCONTROL                    = 0x1004,
    OPINS_CMD_REQ_SENDAUDIO                    = 0x1005,
    OPINS_CMD_RES_SENDAUDIO                    = 0x1006,
    OPINS_CMD_REQ_RELAYCONTROL                 = 0x1007,
    OPINS_CMD_RES_RELAYCONTROL                 = 0x1008,
    OPINS_CMD_REQ_ARCHIVESTATUS                = 0x1009,
    OPINS_CMD_RES_ARCHIVESTATUS                = 0x100A,
    OPINS_CMD_REQ_RECDATEINFO                    = 0x100B,
    OPINS_CMD_RES_RECDATEINFO                    = 0x100C,
    OPINS_CMD_REQ_RECMININFO                    = 0x100D,
    OPINS_CMD_RES_RECMININFO                    = 0x100E,
    OPINS_CMD_REQ_RECFILE                        = 0x100F,
    OPINS_CMD_RES_RECFILE                        = 0x1010,
    OPINS_CMD_REQ_RECIFRAME                    = 0x1011,
    OPINS_CMD_RES_RECIFRAME                    = 0x1012,
    OPINS_CMD_REQ_UPLOADMAPFILE                = 0x10A,

    OPINS_CMD_REQ_DOWNLOADMAPFILE              = 0x10C,
    OPINS_CMD_RES_DOWNLOADMAPFILE              = 0x10D,

    OPINS_CMD_REQ_KEEPALIVE                    = 0x110,
    OPINS_CMD_RES_KEEPALIVE                    = 0x111,

    OPINS_CMD_REQ_STATUSDATA                   = 0x101D,
    OPINS_CMD_RES_STATUSDATA                   = 0x101E



}
